{% set name = "localstack-ext" %}
{% set version = "0.10.54" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 29952e8527c0de349a89a87336e6b4e71d518449697819bc82ad8e7b9e3e2929

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - dnslib
    - dnspython
    - pyaes
    - python

test:
  imports:
    - localstack_ext
    - localstack_ext.bootstrap

about:
  home: "https://github.com/localstack/localstack"
  license: "Apache-2.0"
  license_family: "APACHE"
  license_file: "LICENSE.txt"
  summary: "Extensions for LocalStack"
  doc_url: "https://pypi.org/project/localstack-ext/"
  dev_url: "https://github.com/localstack/localstack"

extra:
  recipe-maintainers:
    - mwilson8
    - oblute
    - benhuff
